version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    restart: always
    env_file:
      - .env
    ports:
      - "8010:8010"
    volumes:
      - .:/usr/src/app
    networks:
      - hris_network

networks:
  hris_network: